spring:
  config:
    import: optional:configserver:http://host.docker.internal:8001
  application:
    name: cloud-feign-example
  profiles:
    active:
      - default
      - dev
  cloud:
    config:
      label: cloud-feign-example
      username: root
      password: root
      fail-fast: false
  devtools:
    livereload:
      port: 35730
server:
  port: 8002