spring:
  config:
    import: optional:configserver:http://127.0.0.1:8001
  application:
    name: cloud-kafka-example
  profiles:
    active:
      - default
      - dev
  cloud:
    config:
      label: cloud-kafka-example
      username: root
      password: root
      fail-fast: false
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          required-acks: 1
      bindings:
        exampleKafkaConsumer-in-0:
          destination: example-kafka-topic
          binder: kafka
          group: example-kafka-group
          producer:
            partition-selector-name: exampleKafkaConsumer
        exampleKafkaFunction-out-0:
          destination: example-kafka-topic
          binder: kafka
          group: example-kafka-group
    function:
      definition: exampleKafkaConsumer
  devtools:
    livereload:
      port: 35532
server:
  port: 8006
