spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/
        bootstrap: true
    zookeeper:
      connect-string: localhost:2181
  profiles:
    active:
      - native
      - dev
  security:
    user:
      name: root
      password: root
  application:
    name: cloud-config-example
  devtools:
    livereload:
      port: 35729
server:
  port: 8001