spring:
  config:
    import: optional:configserver:http://127.0.0.1:8001
  application:
    name: cloud-gateway-example
  profiles:
    active:
      - default
      - dev
  cloud:
    config:
      label: cloud-gateway-example
      username: root
      password: root
      fail-fast: true
  devtools:
    livereload:
      port: 35732
server:
  port: 8004
